"""update-client-profile

Revision ID: 4266e2b64014
Revises: 001
Create Date: 2026-07-17 07:54:42.950530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4266e2b64014'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('places', 'cached_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_places_place_id'), table_name='places')
    op.drop_index(op.f('ix_places_primary_type'), table_name='places')
    op.drop_index(op.f('ix_places_zip_code'), table_name='places')
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_reports_profile_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_uszips_cbsa_name'), table_name='uszips')
    op.drop_index(op.f('ix_uszips_lat_lng'), table_name='uszips')
    op.drop_index(op.f('ix_uszips_state_id'), table_name='uszips')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_uszips_state_id'), 'uszips', ['state_id'], unique=False)
    op.create_index(op.f('ix_uszips_lat_lng'), 'uszips', ['lat', 'lng'], unique=False)
    op.create_index(op.f('ix_uszips_cbsa_name'), 'uszips', ['cbsa_name'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_profile_id'), 'reports', ['profile_id'], unique=False)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_places_zip_code'), 'places', ['zip_code'], unique=False)
    op.create_index(op.f('ix_places_primary_type'), 'places', ['primary_type'], unique=False)
    op.create_index(op.f('ix_places_place_id'), 'places', ['place_id'], unique=False)
    op.alter_column('places', 'cached_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
