"""initial

Revision ID: bb3e5221d186
Revises: 
Create Date: 2026-07-19 12:29:48.082458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb3e5221d186'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('business_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('service_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('competitor_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('complimentary_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_profiles_conversation_id'), 'client_profiles', ['conversation_id'], unique=True)
    op.create_table('uszips',
    sa.Column('zip', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('state_id', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('state_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('zcta', sa.Boolean(), nullable=True),
    sa.Column('parent_zcta', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('population', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('county_fips', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('county_name', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('county_weights', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('county_names_all', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('county_fips_all', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('imprecise', sa.Boolean(), nullable=True),
    sa.Column('military', sa.Boolean(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('age_median', sa.Float(), nullable=True),
    sa.Column('age_under_10', sa.Float(), nullable=True),
    sa.Column('age_10_to_19', sa.Float(), nullable=True),
    sa.Column('age_20s', sa.Float(), nullable=True),
    sa.Column('age_30s', sa.Float(), nullable=True),
    sa.Column('age_40s', sa.Float(), nullable=True),
    sa.Column('age_50s', sa.Float(), nullable=True),
    sa.Column('age_60s', sa.Float(), nullable=True),
    sa.Column('age_70s', sa.Float(), nullable=True),
    sa.Column('age_over_80', sa.Float(), nullable=True),
    sa.Column('age_over_65', sa.Float(), nullable=True),
    sa.Column('age_18_to_24', sa.Float(), nullable=True),
    sa.Column('age_over_18', sa.Float(), nullable=True),
    sa.Column('male', sa.Float(), nullable=True),
    sa.Column('female', sa.Float(), nullable=True),
    sa.Column('married', sa.Float(), nullable=True),
    sa.Column('divorced', sa.Float(), nullable=True),
    sa.Column('never_married', sa.Float(), nullable=True),
    sa.Column('widowed', sa.Float(), nullable=True),
    sa.Column('family_size', sa.Float(), nullable=True),
    sa.Column('family_dual_income', sa.Float(), nullable=True),
    sa.Column('income_household_median', sa.Float(), nullable=True),
    sa.Column('income_household_under_5', sa.Float(), nullable=True),
    sa.Column('income_household_5_to_10', sa.Float(), nullable=True),
    sa.Column('income_household_10_to_15', sa.Float(), nullable=True),
    sa.Column('income_household_15_to_20', sa.Float(), nullable=True),
    sa.Column('income_household_20_to_25', sa.Float(), nullable=True),
    sa.Column('income_household_25_to_35', sa.Float(), nullable=True),
    sa.Column('income_household_35_to_50', sa.Float(), nullable=True),
    sa.Column('income_household_50_to_75', sa.Float(), nullable=True),
    sa.Column('income_household_75_to_100', sa.Float(), nullable=True),
    sa.Column('income_household_100_to_150', sa.Float(), nullable=True),
    sa.Column('income_household_150_over', sa.Float(), nullable=True),
    sa.Column('income_household_six_figure', sa.Float(), nullable=True),
    sa.Column('income_individual_median', sa.Float(), nullable=True),
    sa.Column('home_ownership', sa.Float(), nullable=True),
    sa.Column('housing_units', sa.Float(), nullable=True),
    sa.Column('home_value', sa.Float(), nullable=True),
    sa.Column('rent_median', sa.Float(), nullable=True),
    sa.Column('rent_burden', sa.Float(), nullable=True),
    sa.Column('education_less_highschool', sa.Float(), nullable=True),
    sa.Column('education_highschool', sa.Float(), nullable=True),
    sa.Column('education_some_college', sa.Float(), nullable=True),
    sa.Column('education_bachelors', sa.Float(), nullable=True),
    sa.Column('education_graduate', sa.Float(), nullable=True),
    sa.Column('education_college_or_above', sa.Float(), nullable=True),
    sa.Column('education_stem_degree', sa.Float(), nullable=True),
    sa.Column('labor_force_participation', sa.Float(), nullable=True),
    sa.Column('unemployment_rate', sa.Float(), nullable=True),
    sa.Column('self_employed', sa.Float(), nullable=True),
    sa.Column('farmer', sa.Float(), nullable=True),
    sa.Column('race_white', sa.Float(), nullable=True),
    sa.Column('race_black', sa.Float(), nullable=True),
    sa.Column('race_asian', sa.Float(), nullable=True),
    sa.Column('race_native', sa.Float(), nullable=True),
    sa.Column('race_pacific', sa.Float(), nullable=True),
    sa.Column('race_other', sa.Float(), nullable=True),
    sa.Column('race_multiple', sa.Float(), nullable=True),
    sa.Column('hispanic', sa.Float(), nullable=True),
    sa.Column('disabled', sa.Float(), nullable=True),
    sa.Column('poverty', sa.Float(), nullable=True),
    sa.Column('limited_english', sa.Float(), nullable=True),
    sa.Column('commute_time', sa.Float(), nullable=True),
    sa.Column('health_uninsured', sa.Float(), nullable=True),
    sa.Column('veteran', sa.Float(), nullable=True),
    sa.Column('charitable_givers', sa.Float(), nullable=True),
    sa.Column('cbsa_fips', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('cbsa_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('cbsa_metro', sa.Boolean(), nullable=True),
    sa.Column('csa_fips', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('csa_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('metdiv_fips', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('metdiv_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.PrimaryKeyConstraint('zip')
    )
    op.create_table('demographic_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('demographic_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('constraint_type', sa.String(length=20), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('target_percentage', sa.Float(), nullable=True),
    sa.Column('percentage_operator', sa.String(length=5), nullable=True),
    sa.Column('importance_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demographic_targets_client_profile_id'), 'demographic_targets', ['client_profile_id'], unique=False)
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_table('checkpoint_migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.drop_index(op.f('ix_demographic_targets_client_profile_id'), table_name='demographic_targets')
    op.drop_table('demographic_targets')
    op.drop_table('uszips')
    op.drop_index(op.f('ix_client_profiles_conversation_id'), table_name='client_profiles')
    op.drop_table('client_profiles')
    # ### end Alembic commands ###
