"""System prompts for the Prospector agents."""

from src.prompts.prompts import (
    USER_PERSONA_SYSTEM_PROMPT,
    KEYWORD_GENERATOR_PROMPT,
    INSTAGRAM_AGENT_SYSTEM_PROMPT,
    GOOGLE_AGENT_SYSTEM_PROMPT,
    ORCHESTRATOR_SYSTEM_PROMPT,
)

__all__ = [
    "USER_PERSONA_SYSTEM_PROMPT",
    "KEYWORD_GENERATOR_PROMPT",
    "INSTAGRAM_AGENT_SYSTEM_PROMPT",
    "GOOGLE_AGENT_SYSTEM_PROMPT",
    "ORCHESTRATOR_SYSTEM_PROMPT",
]
